//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RowingMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-0.3572452,-0.3490678,-0.2542619,-0.2011797,-0.1199621,-0.07131882,0.08226088,0.1429305,0.1976377,0.2382801,0.2714247,0.2965077,0.3337264,0.3674536,0.3881752,0.42067,0.4965224,0.5511806,0.5856584,0.6243865,0.6179907,0.5969598,0.5919273,0.58354,0.5530193,0.5355344,0.5215479,0.4970674,0.4621478,0.4317877,0.4165026,0.4100573,0.3656242,0.3362587,0.3210904,0.2998691,0.2605171,0.2313108,0.2089331,0.1573845,0.1066876,0.05716151,0.03672173,0.02068753,-0.07522594,-0.1568682,-0.2491253,-0.2922076,-0.3153023,-0.3269816")]
        public string Template {
            get {
                return ((string)(this["Template"]));
            }
        }
    }
}
