//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RowingMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0,03893804;0,06183462;0,08864907;0,1186831;0,1886777;0,2222317;0,2601413;0,3430829;0,3851423;0,4774551;0,5227016;0,5713651;0,6726766;0,7259682;0,7719128;0,8092774;0,8393533;0,8707815;0,9036884;0,9339333;0,9731057;0,9890426;0,9943504;1;0,9994099;0,9976877;0,9997693;0,989715;0,9753042;0,9650298;0,9513105;0,917571;0,8978924;0,8548411;0,8320903;0,8071542;0,7860036;0,7593648;0,7229874;0,6878539;0,6511027;0,6172103;0,5408154;0,5051584;0,4658352;0,3959738;0,367872;0,3431957;0,3117038;0,2729245;0,2358188;0,2026912;0,1774583;0,1480588;0,1013709;0,08211092;0,06426348;0,0491862;0,03533636;0,02442593;0,01072144;0;0,007211646;0,009775571;0,01237515;0,02140435;0,03769221")]
        public string Template {
            get {
                return ((string)(this["Template"]));
            }
            set {
                this["Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float FootSpineBaseOffset {
            get {
                return ((float)(this["FootSpineBaseOffset"]));
            }
            set {
                this["FootSpineBaseOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public double MinSegmentTime {
            get {
                return ((double)(this["MinSegmentTime"]));
            }
            set {
                this["MinSegmentTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double PeakDetectionWindow {
            get {
                return ((double)(this["PeakDetectionWindow"]));
            }
            set {
                this["PeakDetectionWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.21")]
        public float DTWStartMinimumPosition {
            get {
                return ((float)(this["DTWStartMinimumPosition"]));
            }
            set {
                this["DTWStartMinimumPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.89")]
        public float DTWStartMaximumPosition {
            get {
                return ((float)(this["DTWStartMaximumPosition"]));
            }
            set {
                this["DTWStartMaximumPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float DTWMaxDistance {
            get {
                return ((float)(this["DTWMaxDistance"]));
            }
            set {
                this["DTWMaxDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Mute {
            get {
                return ((bool)(this["Mute"]));
            }
            set {
                this["Mute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayBeep {
            get {
                return ((bool)(this["PlayBeep"]));
            }
            set {
                this["PlayBeep"] = value;
            }
        }
    }
}
