//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RowingMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"-0.2975853,-0.2042504,-0.155101,-0.1192965,-0.07102258,-0.01225698,0.04263343,0.09506955,0.212961,0.3227854,0.4005949,0.4842655,0.5480029,0.6140994,0.6775281,0.864189,0.9901069,1.061857,1.101033,1.080527,1.080753,1.046898,1.013551,0.9809682,0.9177071,0.888526,0.8497285,0.7982491,0.7981368,0.7722788,0.7473091,0.6822425,0.606694,0.572104,0.5203418,0.4954889,0.4527771,0.3436244,0.2572533,0.1368963,0.03032687,-0.04209379,-0.08547286,-0.1280674,-0.1517017,-0.1770424,-0.2377988,-0.2461435,-0.2595812,-0.2688748")]
        public string Template {
            get {
                return ((string)(this["Template"]));
            }
            set {
                this["Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float FootSpineBaseOffset {
            get {
                return ((float)(this["FootSpineBaseOffset"]));
            }
            set {
                this["FootSpineBaseOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.2")]
        public double MinSegmentTime {
            get {
                return ((double)(this["MinSegmentTime"]));
            }
            set {
                this["MinSegmentTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double PeakDetectionWindow {
            get {
                return ((double)(this["PeakDetectionWindow"]));
            }
            set {
                this["PeakDetectionWindow"] = value;
            }
        }
    }
}
